version: "3.8"

services:
    backend:
        build:
            context: ./ph-study-routine-server
            dockerfile: Dockerfile
        volumes:
            - ./ph-study-routine-server:/app
            - /app/node_modules
        ports:
            - "5000:5000"
        environment:
            - NODE_ENV=development
            - MONGODB_URI=mongodb+srv://nafiz002:Nafiz002@cluster0.npgzr.mongodb.net/ph-study-planner?retryWrites=true&w=majority&appName=Cluster0
            - ACCESS_TOKEN_SECRET=Ph-study-planner-@ccess-token
            - STATIC_FILE_URL=http://localhost:5000/static/
            - CLIENT=http://localhost:3000

    frontend:
        build:
            context: ./ph-study-routine-client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
            - NEXT_PUBLIC_SERVER_URL=http://localhost:5000/api/v1
        depends_on:
            - backend

volumes:
    routine_planner:
